"""集成测试：使用 Mock LLM 跑通完整 DAG。"""
import asyncio
import os
from pathlib import Path

# 强制使用 MOCK 模式，避免误调真实 API
os.environ.setdefault("LLM_API_KEY", "")

from dev_agent_system.llm import LLMClient
from dev_agent_system.orchestrator import Orchestrator


def _mock_chat(self, system: str, user: str, **kwargs) -> str:
    """根据 system prompt 中的 Agent 名称返回不同 Mock 内容。"""
    system_lower = system.lower()
    if "architect" in system_lower:
        return '{"modules": ["main"], "api_contract": {"add": "int -> int -> int"}, "tech_stack": "python", "mermaid": "", "notes": ""}'
    if "coder" in system_lower:
        return (
            '# file: main.py\n'
            '```python\n'
            'def add(a, b):\n'
            '    return a + b\n'
            '\n'
            'if __name__ == "__main__":\n'
            '    print(add(1, 2))\n'
            '```\n'
            '\n'
            '```json\n'
            '{"status": "completed", "files_modified": ["main.py"], "test_result": "passed", "note": ""}\n'
            '```'
        )
    if "tester" in system_lower:
        return (
            '# file: test_main.py\n'
            '```python\n'
            'from main import add\n'
            '\n'
            'def test_add():\n'
            '    assert add(1, 2) == 3\n'
            '```\n'
            '\n'
            '```json\n'
            '{"passed": 1, "failed": 0, "coverage": 0.0, "report": "OK"}\n'
            '```'
        )
    if "reviewer" in system_lower:
        return '{"severity": "low", "passed": true, "issues": [], "suggestions": []}'
    if "docs" in system_lower:
        return '# file: README.md\n# Test Project\n\nThis is generated by Docs Agent.\n'
    if "devops" in system_lower:
        return 'DevOps summary'
    return "mock"


def test_orchestrator_end_to_end(monkeypatch):
    monkeypatch.setattr(LLMClient, "chat", _mock_chat)

    async def _run():
        orch = Orchestrator(max_iterations=1)
        result = await orch.run("开发一个加法模块")
        return result

    result = asyncio.run(_run())
    assert result["status"] == "completed"
    assert "architect" in result
    assert "coder" in result
    assert "reviewer" in result
    # 验证产物已写入 workspace
    workspace = Path(result["artifacts"]["workspace"])
    assert (workspace / "main.py").exists()
    assert (workspace / "test_main.py").exists()
    assert (workspace / "review_report.json").exists()


def test_sandbox_path_escape():
    from dev_agent_system.mcp import ToolSandbox
    result = ToolSandbox.read_file("../etc/passwd")
    assert result["success"] is False
    assert "越界" in result["error"]


def test_idempotency_guard():
    from dev_agent_system.orchestrator import IdempotencyGuard
    g = IdempotencyGuard()
    assert g.is_duplicate("req-1") is False
    assert g.is_duplicate("req-1") is True


def test_extract_code_blocks():
    from dev_agent_system.agents import BaseAgent
    text = "# file: foo.py\n```python\nprint(1)\n```"
    blocks = BaseAgent._extract_code_blocks(text)
    assert len(blocks) == 1
    assert blocks[0]["path"] == "foo.py"
