"""Checkpoint 持久化测试：验证 SQLite checkpoint 读写与 Orchestrator 断点续跑。"""
import asyncio
import os
from pathlib import Path

import pytest
from langgraph.checkpoint.base import empty_checkpoint

# 强制 MOCK 模式
os.environ.setdefault("LLM_API_KEY", "")

from dev_agent_system.checkpoint import SQLiteCheckpointSaver, make_checkpointer
from dev_agent_system.llm import LLMClient
from dev_agent_system.orchestrator import Orchestrator


def _mock_chat(self, system: str, user: str, **kwargs) -> str:
    """Mock LLM 输出，与 test_flow.py 保持一致。"""
    system_lower = system.lower()
    if "architect" in system_lower:
        return '{"modules": ["main"], "api_contract": {}, "tech_stack": "python", "mermaid": "", "notes": ""}'
    if "coder" in system_lower:
        return (
            '# file: main.py\n'
            '```python\n'
            'def add(a, b):\n'
            '    return a + b\n'
            '\n'
            'if __name__ == "__main__":\n'
            '    print(add(1, 2))\n'
            '```\n'
            '\n'
            '```json\n'
            '{"status": "completed", "files_modified": ["main.py"], "test_result": "passed", "note": ""}\n'
            '```'
        )
    if "tester" in system_lower:
        return (
            '# file: test_main.py\n'
            '```python\n'
            'from main import add\n'
            '\n'
            'def test_add():\n'
            '    assert add(1, 2) == 3\n'
            '```\n'
            '\n'
            '```json\n'
            '{"passed": 1, "failed": 0, "coverage": 0.0, "report": "OK"}\n'
            '```'
        )
    if "reviewer" in system_lower:
        return '{"severity": "low", "passed": true, "issues": [], "suggestions": []}'
    if "docs" in system_lower:
        return '# file: README.md\n# Test Project\n\nGenerated by Docs Agent.\n'
    return "mock"


def test_sqlite_checkpoint_put_and_get(tmp_path):
    db = tmp_path / "ckpt.sqlite"
    saver = SQLiteCheckpointSaver(db_path=str(db))

    config = {"configurable": {"thread_id": "req-1", "checkpoint_ns": ""}}
    checkpoint = empty_checkpoint()
    metadata = {"source": "input", "step": -1, "writes": {}, "parents": {}}

    saver.put(config, checkpoint, metadata, {})
    result = saver.get_tuple({"configurable": {"thread_id": "req-1"}})

    assert result is not None
    assert result.checkpoint["id"] == checkpoint["id"]
    assert result.metadata["source"] == "input"
    assert result.checkpoint.get("pending_sends") == []


def test_sqlite_checkpoint_put_writes_and_list(tmp_path):
    db = tmp_path / "ckpt.sqlite"
    saver = SQLiteCheckpointSaver(db_path=str(db))

    config = {"configurable": {"thread_id": "req-2", "checkpoint_ns": ""}}
    checkpoint = empty_checkpoint()
    metadata = {"source": "loop", "step": 0, "writes": {}, "parents": {}}

    new_config = saver.put(config, checkpoint, metadata, {})
    saver.put_writes(new_config, [("channel1", "value1"), ("channel2", "value2")], "task-1")

    result = saver.get_tuple({"configurable": {"thread_id": "req-2"}})
    assert result is not None
    assert len(result.pending_writes) == 2
    channels = {w[1] for w in result.pending_writes}
    assert channels == {"channel1", "channel2"}

    checkpoints = list(saver.list({"configurable": {"thread_id": "req-2"}}))
    assert len(checkpoints) == 1


def test_checkpoint_make_checkpointer(tmp_path, monkeypatch):
    """确认 make_checkpointer 在启用状态下返回 SQLite saver。"""
    monkeypatch.setenv("CHECKPOINT_ENABLED", "true")
    monkeypatch.setenv("CHECKPOINT_DB", str(tmp_path / "ckpt.sqlite"))
    checkpointer = make_checkpointer()
    assert isinstance(checkpointer, SQLiteCheckpointSaver)


def test_orchestrator_persists_checkpoints(monkeypatch, tmp_path):
    """Orchestrator 执行后应产生 checkpoint，并能恢复至最终状态。"""
    monkeypatch.setattr(LLMClient, "chat", _mock_chat)
    monkeypatch.setenv("CHECKPOINT_DB", str(tmp_path / "ckpt.sqlite"))
    monkeypatch.setenv("CHECKPOINT_ENABLED", "true")

    async def _run():
        orch = Orchestrator(max_iterations=1)
        result = await orch.run("开发一个加法模块", request_id="ckpt-req-3")
        checkpoints = orch.list_checkpoints("ckpt-req-3")
        return result, checkpoints

    result, checkpoints = asyncio.run(_run())

    assert result["request_id"] == "ckpt-req-3"
    assert result["status"] == "completed"
    assert checkpoints
    assert Path(result["artifacts"]["workspace"]).exists()


def test_orchestrator_resume_from_checkpoint(monkeypatch, tmp_path):
    """先跑一次任务，再 resume；resume 应返回已完成的最终状态。"""
    monkeypatch.setattr(LLMClient, "chat", _mock_chat)
    monkeypatch.setenv("CHECKPOINT_DB", str(tmp_path / "ckpt.sqlite"))
    monkeypatch.setenv("CHECKPOINT_ENABLED", "true")

    async def _run_and_resume():
        orch = Orchestrator(max_iterations=1)
        first = await orch.run("开发一个加法模块", request_id="ckpt-req-4")
        resumed = await orch.resume("ckpt-req-4")
        return first, resumed

    first, resumed = asyncio.run(_run_and_resume())

    assert first["request_id"] == "ckpt-req-4"
    assert resumed["request_id"] == "ckpt-req-4"
    assert resumed["status"] == "completed"
